### ISSUE TITLE
Failed to fetch parent block

### ISSUE THREAD

**Issue by danhowitt** [AugurProject/augur-node#513]
Bug when syncing. It doesn't crash out but does log an error all the same. 

```
{"id":37112,"jsonrpc":"2.0","method":"getMarketPriceCandlesticks","params":{"marketId":"0x5d192f598ff29318013b3f269ae37590aa75b5f9","period":3600,"start":1531148400,"end":1531236410,"outcome":"1"}}
[16:28:16.823] [info] {"id":37112,"jsonrpc":"2.0","method":"getMarketPriceCandlesticks","params":{"marketId":"0x5d192f598ff29318013b3f269ae37590aa75b5f9","period":3600,"start":1531148400,"end":1531236410,"outcome":"1"}}
[16:28:16.873] [info]
[16:28:18.285] [info]
Error: Failed to fetch parent block.
    at Object.<anonymous> (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:106:27)
    at step (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:32:23)
    at Object.next (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:13:53)
    at fulfilled (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Augur app 1.0.0. Infura https://mainnet.infura.io/augur and wss://mainnet.infura.io

**Comment by bthaile** [comment]
`Failed to fetch parent block` can safely be ignored, Issue originating from Infura. 
"It is just Infura returning results that don't make sense."

**Comment by bthaile** [comment]
Download bersion 1.0.3, the message should go away.
