### ISSUE TITLE
Failed to startup: Invalid chunkSize: 0

### ISSUE THREAD

**Issue by danhowitt** [AugurProject/augur-node#520]
Occasionally getting this exception:

Augur app version v1.0.2

```
[19:37:24.647] [info] Failed to startup: Invalid chunkSize: 0
Unhandled rejection TypeError: Invalid chunkSize: 0
    at wrapper.returning._returning (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:61:21)
    at Promise._execute (/Users/dan/dev/dan_howitt/augur-app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/dan/dev/dan_howitt/augur-app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/dan/dev/dan_howitt/augur-app/node_modules/bluebird/js/release/promise.js:79:10)
    at batchInsert (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:57:39)
    at Function.batchInsert (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/knex/lib/util/make-knex.js:68:40)
    at async_1.parallel (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:111:32)
    at /Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)
    at _parallel (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3948:5)
    at async_1.forEachOf (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:106:29)
    at /Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1043:9)
    at Object.eachOf (/Users/dan/dev/dan_howitt/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)

[19:37:24.663] [error] Error: aborted
    at PendingOperation.abort (/Users/dan/dev/dan_howitt/augur-app/node_modules/tarn/lib/PendingOperation.js:25:17)
    at Promise.all.pendingAcquires.map.acquire (/Users/dan/dev/dan_howitt/augur-app/node_modules/tarn/lib/Pool.js:190:23)
    at Array.map (<anonymous>)
    at Promise.all.then.then (/Users/dan/dev/dan_howitt/augur-app/node_modules/tarn/lib/Pool.js:189:34)
    at <anonymous>

(node:34342) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Object has been destroyed
```

**Comment by petervecchiarelli** [comment]
Dupe
