### ISSUE TITLE
Install packages fails

### ISSUE THREAD

**Issue by zach-is-my-name** [AugurProject/augur-node#538]
Ubuntu 16.10
Node 8.11.3

../../augur-node$ sudo npm run build
(good)

../../augur-node$ sudo npm install

Symlinking shared-git-hooks runner in .git/hooks

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/zmg/Projects/augusti/augur-node/node_modules/shared-git-hooks/hook.sh'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.saveHookRunner (/home/zmg/Projects/augusti/augur-node/node_modules/shared-git-hooks/index.js:27:6)
    at installHooks (/home/zmg/Projects/augusti/augur-node/node_modules/shared-git-hooks/index.js:72:11)
    at Object.<anonymous> (/home/zmg/Projects/augusti/augur-node/node_modules/shared-git-hooks/index.js:89:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by zach-is-my-name** [comment]
Resolved with chmod +rwx '/home/zmg/Projects/augusti/augur-node/.git/hooks

**Comment by nojacko** [comment]
You don't need to use sudo to install Augur node.
