### ISSUE TITLE
run clean-start: cannot find module

### ISSUE THREAD

**Issue by zach-is-my-name** [AugurProject/augur-node#540]
> augur-node@5.0.0-15 start /home/zmg/Projects/augusti/augur-node
> node ./build/runServer

module.js:549
    throw err;
    ^

Error: Cannot find module '/home/zmg/Projects/augusti/augur-node/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/zmg/Projects/augusti/augur-node/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/zmg/Projects/augusti/augur-node/build/setup/check-and-initialize-augur-db.js:13:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by zach-is-my-name** [comment]
Resolved with https://github.com/mapbox/node-sqlite3/issues/687
