### ISSUE TITLE
Websocket fails after changing env var

### ISSUE THREAD

**Issue by zach-is-my-name** [AugurProject/augur-node#542]
> $ export ETHEREUM_HTTP=https://rinkeby.ethereum.nodes.augur.net 
> $ export ETHEREUM_WS=wss://websocket-rinkeby.ethereum.nodes.augur.net

```
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://localhost:8545","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
could not connect to ethereum-node at {"http":"http://localhost:8545","ws":"http://localhost:8546"} {}
Fatal Error: Error: Could not connect via augur.connect Error: Connection failed
    at Object.<anonymous> (/home/zmg/Projects/augusti/augur-node/build/setup/check-and-initialize-augur-db.js:59:35)
    at Generator.next (<anonymous>)
    at /home/zmg/Projects/augusti/augur-node/build/setup/check-and-initialize-augur-db.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/zmg/Projects/augusti/augur-node/build/setup/check-and-initialize-augur-db.js:3:12)
    at augur.connect (/home/zmg/Projects/augusti/augur-node/build/setup/check-and-initialize-augur-db.js:57:52)
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/src/connect/index.js:107:75
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/node_modules/async/lib/async.js:726:13
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/node_modules/async/lib/async.js:52:16
    at done (/home/zmg/Projects/augusti/augur-node/node_modules/augur.js/node_modules/async/lib/async.js:246:17)
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/node_modules/async/lib/async.js:44:16
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/node_modules/async/lib/async.js:723:17
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/node_modules/async/lib/async.js:167:37
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/src/connect/index.js:89:18
    at /home/zmg/Projects/augusti/augur-node/node_modules/augur.js/src/connect/connect-to-ethereum.js:16:21
    at /home/zmg/Projects/augusti/augur-node/node_modules/ethrpc/src/connect.js:48:23
```

**Comment by zach-is-my-name** [comment]
Resolved: invoking with sudo npm run clean-start kills env vars
