### ISSUE TITLE
No longer able to sync with infura: Error: query returned more than 1000 results

### ISSUE THREAD

**Issue by SebastianMetzger** [AugurProject/augur-node#848]
This started about 2-3 days ago, I actually suspect infura changed sth regarding API limits.

I used a rather old version of augur-node, but used the latest master and had the same error, even after resetting the db and trying to resync from scratch (actually it failed at a block from 2018 in that instance, which makes me believe that infura changed something here).

I already contacted the infura support, but maybe it is a change on infuras site regarding api limits, that you have to incoporate as well?

```
new block: 5934066, 1531153769 (Mon Jul 09 2018 16:29:29 GMT+0000 (Coordinated Universal Time))
Processing 1 logs
query returned more than 1000 results
Error: query returned more than 1000 results
    at parseEthereumResponse (/home/ec2-user/new-augur-node/augur-node/node_modules/augur.js/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)
    at responseHandler (/home/ec2-user/new-augur-node/augur-node/node_modules/augur.js/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:46:7)
    at errorHandler (/home/ec2-user/new-augur-node/augur-node/node_modules/augur.js/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:36:16)
    at /home/ec2-user/new-augur-node/augur-node/node_modules/augur.js/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:55:7
    at store.dispatch (/home/ec2-user/new-augur-node/augur-node/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/home/ec2-user/new-augur-node/augur-node/node_modules/augur.js/node_modules/ethrpc/src/reset-state.js:45:9)
    at WsTransport.<anonymous> (/home/ec2-user/new-augur-node/augur-node/node_modules/augur.js/node_modules/ethrpc/src/transport/ws-transport.js:57:5)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/ec2-user/new-augur-node/augur-node/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/home/ec2-user/new-augur-node/augur-node/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/ec2-user/new-augur-node/augur-node/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:182:13)
    at WebSocketConnection.processFrame (/home/ec2-user/new-augur-node/augur-node/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/ec2-user/new-augur-node/augur-node/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at process._tickCallback (internal/process/next_tick.js:61:11)
Stopping Augur Node Server
```

**Comment by pgebheim** [comment]
Thanks for reporting this. We'll put in the log fetch limit for infura in the next version.

**Comment by pgebheim** [comment]
Pushing a brach now to let you configure how many blocks to fetch with an environment variable.

```
BLOCKS_PER_CHUNK=10 yarn start
```

Should then work for syncing against infura.

**Comment by SebastianMetzger** [comment]
Yes, it ran for couple of weeks and stopped couple of days ago at a certain block.

I tried a complete resync and it stopped at a block from 2018.

Thx for the quick fix, will try it tomorrow 💪

**Comment by SebastianMetzger** [comment]
@pgebheim FYI: Got the sync to run again and it even passed the block that caused the error already, but I had to set the limit rediculously low. It still errored with 16 blocks per chunk and it seems to work now with 8 blocks per chunk 🙈

**Comment by pgebheim** [comment]
Yeah, I got it working with 10 blocks per chunk.

Issue with then complete resync is that is that the first couple hundred blocks are stuffed with transfers from the rep migration, which means lots of logs.

You can probably stop it and crank it up again after the initial set of blocks is done.

May I suggest not using Infura? Augur App now ships with a key for Alchemy which they are generously providing for Augur users.

Paul
paul@augur.net

________________________________
