### ISSUE TITLE
Could not find balance for token decrease (token:

### ISSUE THREAD

**Issue by SebastianMetzger** [AugurProject/augur-node#852]
Aftter my issue with the request limit of infura (https://github.com/AugurProject/augur-node/issues/848), the sync now stopped at another block with the following error:
```
Fetching blocks details from 6832112 to 6832112
new block: 6832104, 1544034910 (Wed Dec 05 2018 18:35:10 GMT+0000 (Coordinated Universal Time))                           
Processing 8 logs
Could not find balance for token decrease (token: 0x1985365e9f78359a9b6ad760e32412f4a445e862, owner: 0xc6a07b6cf5b3295ff1fef54e6c6e35a44d0db2b1)
Error: Could not find balance for token decrease (token: 0x1985365e9f78359a9b6ad760e32412f4a445e862, owner: 0xc6a07b6cf5b3295ff1fef54e6c6e35a44d0db2b1)
    at Object.<anonymous> (/home/ec2-user/new-augur-node/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:20:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ec2-user/new-augur-node/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:4:58)
```

I get the same error using infura and the alchemy node (also the alchemy node gave me a rate limit error after a while)

**Comment by pgebheim** [comment]
@SebastianMetzger You need to delete your database and re-sync. This error is a symptom of a corrupt database.
